{% set name = "dem_stitcher" %}
{% set version = "2.5.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c01a80dd8d5a70fb6e3c8440331ddcf1bed95278b4423f41604ccdd37c4aae5f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=42
    - setuptools_scm >=3.4
    - wheel
  run:
    - python >={{ python_min }}
    - affine
    - boto3
    - geopandas
    - importlib-metadata
    - numpy
    - pyproj
    - rasterio
    - requests
    - shapely
    - tqdm

test:
  imports:
    - dem_stitcher
    - dem_stitcher.stitcher
    - dem_stitcher.datasets
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/ACCESS-Cloud-Based-InSAR/dem-stitcher
  summary: Download and merge DEM tiles
  description: |
    This tool aims to (a) provide a continuous raster of Digital Elevation Raster over an area of interest and (b) perform some standard transformations for processing. Such transformations include:
      + converting the vertical datum from a reference geoid to the WGS84 ellipsoidal
      + ensuring a coordinate reference system centered at either the upper-left corner (`Area` tag) or center of the pixel (`Point` tag).

    We utilize the GIS formats from `rasterio`. This tool was developed to support cloud SAR processing using ISCE2 and various research. The early work of this repository was done by Charlie Marshak, David Bekaert, Michael Denbina, and Marc Simard.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://github.com/ACCESS-Cloud-Based-InSAR/dem-stitcher
  dev_url: https://github.com/ACCESS-Cloud-Based-InSAR/dem-stitcher

extra:
  recipe-maintainers:
    - cmarshak
    - jhkennedy
